### ISSUE TITLE
能否添加友盟推送呢？

### ISSUE THREAD

**Issue by xiaowx2010** [pengyuantao/OnePush#1]
或者自己添加新的推送的话，需要做些什么工作呢？

**Comment by pengyuantao** [comment]
详见说明文档【关于添加其他消息推送SDK具体操作（如果你不满足OnePush提供的小米、华为推送，可根据下面步骤，将其他厂商提供的推送，添加到OnePush里面）】

【建议】重新创建一个library，类似于demo的one-push-xiaomi，添加   provided 'com.peng.library:one-push-core:1.0.1'依赖。

**Comment by xiaowx2010** [comment]
现在华为好像在推HMS服务，后面华为单独的push服务好像就会被取消=。=

**Comment by pengyuantao** [comment]
是的，这个问题问过华为的技术人员，华为在推HMS服务，不过目前HMS没有setTag的功能，所有OnePush没有使用HMS服务作为华为服务推送支持，等后期HMS服务支持setTag后，再进行升级。
