### ISSUE TITLE
华为推送 旧版的已经不再维护了

### ISSUE THREAD

**Issue by youmu178** [pengyuantao/OnePush#11]
新版的不太适应这个拓展

**Comment by pengyuantao** [comment]
我一直在关注华为推送，目前华为HMS还不支持标签的设置，不过总体上的流程都是差不多的，可以对HMS进行拓展。目前HMS还有很多功能不完善，原来的setTag/getTag/deleteTag功能暂时不可用，不过老版本的也是同样不能使用了，近期会对HMS进行适配，请持续关注。HMS服务文档：http://developer.huawei.com/consumer/cn/service/hms/catalog/huaweipush.html?page=hmssdk_huaweipush_devguide

**Comment by youmu178** [comment]
我已经弄好了。等会push下

**Comment by kinzirva** [comment]
什么时候能push上来呀，大兄弟

**Comment by youmu178** [comment]
没有权限提不上去

**Comment by youmu178** [comment]
已经提交
