### ISSUE TITLE
友盟是可以获取通知的信息的

### ISSUE THREAD

**Issue by xiaolong5477** [pengyuantao/OnePush#13]
public class OnePushMessageHandler extends UmengMessageHandler {

    @Override
    public void dealWithCustomMessage(Context context, UMessage uMessage) {
        OneRepeater.transmitMessage(context, uMessage.custom, null, uMessage.extra);
    }
}
这里面重写
@Override
 public Notification getNotification(Context context, UMessage uMessage)
这个方法是可以获取通知的信息的，望博主加上

**Comment by pengyuantao** [comment]
已修复，谢谢反馈
