### ISSUE TITLE
友盟推送弹出mPushAgent.register should be called in both main process and channel process! 的Toast

### ISSUE THREAD

**Issue by xiaolong5477** [pengyuantao/OnePush#14]
官方给出的解决方案http://bbs.umeng.com/thread-22209-1-1.html
或者是调用mPushAgent.setDebugMode(false)关闭Debug模式

**Comment by pengyuantao** [comment]
你好，你是按照下面的方式注册友盟推送的吗？

![default](https://user-images.githubusercontent.com/10327185/32318871-8e0038c4-bff3-11e7-842f-ab0810e6af4a.png)
