### ISSUE TITLE
集成多家推送推送消息重复？

### ISSUE THREAD

**Issue by lucheng0522** [pengyuantao/OnePush#17]
如果集成了小米 华为 友盟推送，同一条推送消息是否在APP上收到多次消息

**Comment by pengyuantao** [comment]
正常情况下，OnePush只会注册激活一个推送通道，如果你通过反射注册其他的推送通道，那么就有可能出现多次消息的情况。当然更好的方式，是服务端维护，根据不同的手机，按照不同的通道推送消息，那么就不会出现重复消息的情况。
