### ISSUE TITLE
为什么没有苹果APN的支持？

### ISSUE THREAD

**Issue by xlight** [pengyuantao/OnePush#18]
服务端还是要分别推苹果和安卓还是太麻烦了吧？
咱们有添加APN支持的计划吗？

**Comment by pengyuantao** [comment]
是的，服务端的确需要区分Android和苹果进行推送，OnePush目前着重解决的Android手机推送送达率的工具，它不是一个平台，所以后期应该不会添加对APN的支持。不知道有没有解决你的问题。
