### ISSUE TITLE
友盟推送相关

### ISSUE THREAD

**Issue by xiaowx2010** [pengyuantao/OnePush#2]
作者大大实在给力，才提出了友盟推送的需求，就给出了支持。先谢谢了
简单阅读代码之后，冒昧提几个建议
1. 现在友盟提供带透传和不带透传的两个版本，不知道作者用的是哪一个呢~
2. utdid4all-1.1.5.3_proguard.jar 这个jar包在一些集成了淘宝SDK的项目中，可能会造成包冲突的问题
3. SDK中直接下载的so文件是不全的，需要适配更多平台的话，还需要额外下载。
不知道能不能通过什么办法能让开发者自己适配呢

**Comment by pengyuantao** [comment]
谢谢反馈哈！
1. 目前用的是带透传消息的版本，似乎没有找到不带透传消息的版本，如果有链接，发个过来看看。
2. 你的第2和第3个问题，说明文档第9条说明，可以完美解决。
再次感谢对OnePush的支持。

**Comment by xiaowx2010** [comment]
可能是我表述的不对，是应用内消息。
友盟的3.1.1版有一个3.1.1a的版本。这个支持应用内消息。可以看下面这个链接
http://dev.umeng.com/push/android/sdk-download
应该的,我们共同学习。
也感谢您正好在boss发飙华为收不到推送的时候，给出了这个解决方案 :)

**Comment by pengyuantao** [comment]
目前onepush用的就是3.1.1a版本

**Comment by xiaowx2010** [comment]
恩，刚刚在文档里看到了。
再次感谢
