### ISSUE TITLE
华为推送返回token为null 具体为 {statusCode: 907135003, statusMessage: null, pendingIntent: null, }

### ISSUE THREAD

**Issue by a1265137718** [pengyuantao/OnePush#21]
```
  HuaweiPush.HuaweiPushApi.getToken(huaweiApiClient)
        .setResultCallback(new ResultCallback<TokenResult>() {
          @Override
          public void onResult(TokenResult tokenResult) {
            OneLog.i("token " + tokenResult.getTokenRes());
            if (tokenResult.getTokenRes() != null && !TextUtils.isEmpty(
                tokenResult.getTokenRes().getToken())) {
              OneRepeater.transmitCommandResult(HMSPushClient.this.context, OnePush.TYPE_REGISTER,
                  OnePush.RESULT_OK, tokenResult.getTokenRes().getToken(), null, null);
            }
          }
        });
```
{statusCode: 907135003, statusMessage: null, pendingIntent: null, }
在 [文档](http://developer.huawei.com/consumer/cn/service/hms/catalog/huaweipush_agent.html?page=hmssdk_huaweipush_api_reference_errorcode) 中 
![通用错误码截图](https://user-images.githubusercontent.com/17821274/34701866-88f27d62-f525-11e7-93ac-4f0951c918d9.png)

**Comment by pengyuantao** [comment]
好的，谢谢反馈，这周末完善一下hms错误方面。

**Comment by hegaojian** [comment]
我也是有这个问题啊，小米 魅族 都好了就差这个华为了

**Comment by a1265137718** [comment]
作者辛苦下，可以检查huawei hms推送渠道的问题吗，这个问题有解决方案了吗？

**Comment by zhangxiongxiong** [comment]
能对应吗

**Comment by hegaojian** [comment]
是华为系统的原因 ，emui 5.0以下的华为手机大部分不支持huawei hms，只有5.0以上的没问题

**Comment by zhangxiongxiong** [comment]
不是华为手机也不行？

**Comment by zhangxiongxiong** [comment]
@pengyuantao 
尝试修改了下，测试成功
修改点1：HMSPushClient类register函数中的getToken(); 我觉得没有很大必要。进行了删除
修改点2：修改把华为手机中的 “华为移动云服务” 更新到最新

**Comment by pengyuantao** [comment]
@zhangxiongxiong 获取不到token，后台是根据什么给你推呢，移动云服务，这个更新是在EMUI多少上面？

**Comment by zhangxiongxiong** [comment]
@pengyuantao 
①虽然删除了HMSPushClient类register函数中的getToken();
但是，HuaweiApiClient 初始化的时候，有成功回调接口，在那个里面进行了getToken。

②华为7.0，在华为自带的应用商城可以查看。
