### ISSUE TITLE
能否添加ReactNative的实现？

### ISSUE THREAD

**Issue by duzliang** [pengyuantao/OnePush#22]
现在用ReactNative的场景较多，且大多都是前端开发，对移动端开发不太懂，若能集成ReactNative，可以方便这方面的同学使用

**Comment by pengyuantao** [comment]
可以考虑，不过目前没有仔细研究过RN，如果有需要的话，我可以提供相应的支持。

**Comment by duzliang** [comment]
RN现在用的还是比较多的，但是比较成熟的推送库很少，有也是刚出来问题很多，有的基本不能用。这个库看着很成熟，如果能加一层RN的支持，也会方便很多
