### ISSUE TITLE
gradle build fail

### ISSUE THREAD

**Issue by duzliang** [pengyuantao/OnePush#24]
`Error:Unable to load class 'org.gradle.api.internal.component.Usage'.
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a></li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
<a href="stopGradleDaemons">Stop Gradle build processes (requires restart)</a></li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.`

**Comment by pengyuantao** [comment]
检查一下是不是升级到Android3.0导致的

**Comment by duzliang** [comment]
现在是AndroidStudio3.0.1

**Comment by duzliang** [comment]
该问题是由于`com.novoda:bintray-release:0.4.0`引起的，升级到**0.5.0**后就可以了
