### ISSUE TITLE
友盟推送还有个问题

### ISSUE THREAD

**Issue by xiaowx2010** [pengyuantao/OnePush#3]
友盟推送有一个需要统计设备是否在线的操作
>在所有的Activity 的onCreate 方法或在应用的BaseActivity的onCreate方法中添加：
>PushAgent.getInstance(context).onAppStart();

详情见 http://dev.umeng.com/push/android/integration#3_2_6

再提一个建议，我现在都是在注册成功后将token缓存起来。
我们OnePush是否可以直接实现这个接口，注册后缓存token，当缓存失效后。可以去服务器获取并返回~

**Comment by pengyuantao** [comment]
OnePush关心的业务就是推送，不关心app日活，不过友盟推送似乎和日活相关了。

至于第一个问题，你完全可以在Activity的onCreate()中，先用OnePush.getPushPlatFormCode()方法判断当前使用的推送是不是友盟，如果是友盟，那么再调用PushAgent.getInstance(context).onAppStart();，毕竟友盟推送和日活相关的，而其他推送和它相关。

那么第二个问题，我当时在写OnePush的时候，已经考虑到是否缓存token的问题，最后决定不进行缓存，为了更好的拓展性。第二个问题，你完全可以自己写一个PushTokenManager的一个类，专门管理推送消息的token，至于你说的缓存失效重新获取的逻辑，也可以全部挪到PushTokenManager类里，所以它不属于OnePush的业务范畴。

**Comment by pengyuantao** [comment]
关于PushAgent.getInstance(context).onAppStart();调用，不需要在外面的进行处理了，one-push-umeng已进行处理，请注意查看最新的更新。
