### ISSUE TITLE
Android Studio3.0报错

### ISSUE THREAD

**Issue by pgsheng** [pengyuantao/OnePush#31]
Error:com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Android-project\AndroidStudioProjects\XXX\Lib_Common\build\intermediates\intermediate-jars\debug\classes.jar
Error:com.android.builder.dexing.DexArchiveBuilderException: Error while dexing com/XXX/common/base/BaseApplication.class
Error:com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Android-project\AndroidStudioProjects\XXX\Lib_Common\build\intermediates\intermediate-jars\debug\classes.jar
Error:com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26)
Error:Execution failed for task ':Module_App:transformClassesWithDexBuilderForDebug'.
com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Android-project\AndroidStudioProjects\XXX\Lib_Common\build\intermediates\intermediate-jars\debug\classes.jar

**Comment by pengyuantao** [comment]
clean重新编译下，我这边AS3.0正常
