### ISSUE TITLE
onReceiveNotification

### ISSUE THREAD

**Issue by zhangxiongxiong** [pengyuantao/OnePush#33]
@pengyuantao 
onReceiveNotification已经废弃。
有替代的函数吗

**Comment by pengyuantao** [comment]
onReceiveNotificationClick

**Comment by zhangxiongxiong** [comment]
@pengyuantao 
这个函数不是点击接受到的消息时才收到的吗

**Comment by pengyuantao** [comment]
是的，这个函数比较靠谱，onReceiveNotification在app被杀死的情况下，是没法得到调用的。
