### ISSUE TITLE
华为应用商店审核失败，原因：请集成HMSAgent。  是不是华为push少集成HMSAgent，还是其他情况！

### ISSUE THREAD

**Issue by oneal23** [pengyuantao/OnePush#35]

**Comment by pengyuantao** [comment]
当前华为HMS推送使用的版本是2.5的，目前华为已经升级到2.6，这两个版本，api变动的比较大，目前较忙暂未适配，后期有进行适配的计划，你可以仿照当前拓展的方式，进行拓展。

**Comment by oneal23** [comment]
哦， 好的

**Comment by nileopen** [comment]
https://github.com/nileopen/OnePush  该fork已添加华为推送sdk2.6.0 ：one-push-huawei-hmsagents
