### ISSUE TITLE
判断型号有误

### ISSUE THREAD

**Issue by DonnyHe** [pengyuantao/OnePush#4]
我使用小米5c，最终注册为友盟推送。大概看了下，在OnePushContext.init()方法里面，遍历时，map中的顺序为华为，友盟，小米，走到友盟后就跳出了循环

**Comment by pengyuantao** [comment]
/**
     * 判断是否为小米系统
     */
    public static boolean isMiuiRom() {
        return !TextUtils.isEmpty(getSystemProperty("ro.miui.ui.version.name"));
    }

目前没有小米5c手机，可以帮我看看，这个方法返回的true吗？
如果是true，你的检查下面，你所设置的platformCode和AndroidManifest.xml中设置的是不是一样的。
![default](https://user-images.githubusercontent.com/10327185/28161598-b259b24a-67f6-11e7-9069-1c9a491d642e.png)
如果是false，那么就说明判断MIUI系统的方法，在小米5c上不能给出正确结果，可能和MIUI版本相关。

**Comment by pengyuantao** [comment]
//注册的时候，这样判断就行了

 //platformCode和platformName就是在<meta/>标签中，对应的"平台标识码"和平台名称
                if (RomUtils.isMiuiRom()) {
                    return platformCode == 101;
                } else if (RomUtils.isHuaweiRom()) {
                    return platformCode == 102;
                } else {
                    return platformCode == 103;
                }
