### ISSUE TITLE
多余support依赖会导致版本冲突问题（作者弃坑了？）

### ISSUE THREAD

**Issue by BrightVan** [pengyuantao/OnePush#40]
我看了下源码，根本就没有用到v7包，但还是依赖了，比如one-push-getui,one-push-meizu,huawei等等。即使依赖了，也可以写成compileonly。
Android studio新版早就用了新的命令implementation等。
作者是不是弃坑了？

**Comment by pengyuantao** [comment]
最近比较忙，没有进行维护，明天统一进行维护。
