### ISSUE TITLE
Android 8.0 不能用静态广播

### ISSUE THREAD

**Issue by BrightVan** [pengyuantao/OnePush#42]
看了源码，收到推送会发送广播，但测试时发现并没有回调自己的实现。后来想起8.0静态广播的限制。可能要采取动态注册的方式。

**Comment by pengyuantao** [comment]
根据官方文档，显示的广播是没有问题的

**Comment by BrightVan** [comment]
搞不清重点啊，就按照readme写是不行的。重点在于，按照目前源码的写法，继承BaseOnePushReceiver，怎么可能显示呢？

**Comment by pengyuantao** [comment]
OnePush目前还是不兼容的8.0，这个得一个个更新第三方的推送平台，如果第三方推送平台不支持8.0的话，那OnePush也是没有办法的。

**Comment by BrightVan** [comment]
可以在Application里动态注册啊，可以在readme里提一下。

**Comment by pengyuantao** [comment]
建议切换友盟的聚合推送（https://developer.umeng.com/docs/66632/detail/66744#h2--push-3434），毕竟这个是平台级别的，他们应该有一个团队进行维护

**Comment by BrightVan** [comment]
它这个是集成了多套推送？不像啊。主要还是怕推送进程被杀，所以需要集成小米之类的系统级推送。

**Comment by vicc1024** [comment]
下面有各大厂商的推送通道，里面的策略就是如果应用被杀死，就会走厂商的通道，和OnePush的效果差不多
