### ISSUE TITLE
为什么小米权限不放在 one-push-xiaomi里面呢

### ISSUE THREAD

**Issue by abwbw** [pengyuantao/OnePush#5]
为什么 <uses-permission android:name="com.peng.one.push.permission.MIPUSH_RECEIVE" />不放 one-push-xiaomi里面呢？直接用
<uses-permission android:name="${applicationId}.permission.MIPUSH_RECEIVE" /> 代替

**Comment by pengyuantao** [comment]
<uses-permission android:name="com.peng.one.push.permission.MIPUSH_RECEIVE" />
这个里面的“com.peng.one.push”是自己应用程序的applicationId。每个应用程序需要配置的不一样，所以就没有必要放在one-push-xiaom里面了

**Comment by abwbw** [comment]
打包aar的时这个{$applicationId}会携带到所引用的apk，编译时在根据apk gradle所配置的applicationId替换，如果使用包名的变量就是该变量，可以直接把这些配置迁移到对应的模块下吗？

**Comment by pengyuantao** [comment]
如果app使用的applicationId和library在Manifest.xml中配置<uses-permission android:name="{$applicationId}.permission.MIPUSH_RECEIVE" />的application是一样的，那么app中就不用设置的了，这些配置会合并到app里面。
