### ISSUE TITLE
可以添加信鸽推送么？

### ISSUE THREAD

**Issue by vihuela** [pengyuantao/OnePush#6]

**Comment by vihuela** [comment]
好懒的。。。（别打我）

**Comment by pengyuantao** [comment]
说实话，个人感觉信鸽推送真不咋地，我们最后都换掉了，如果你有这样的需求，看看最近有空的话，也可以把信鸽加上

**Comment by vihuela** [comment]
@pengyuantao 这里主要考虑到一个问题，后台集成和推送测试，这个库后台集成不是要到各个平台获取文档么？我们自己测试时也需要到各个平台测试？嘿嘿~

**Comment by pengyuantao** [comment]
因为后台开发的语言不见得一样，我这里只是提供了小米、华为后台java版的代码示例，如果后台用的不是java语言的话，那还是需要使用对应的语言进行开发，所以肯定要到每一个平台测试一下，这样保险点。
