### ISSUE TITLE
小米控制台发送消息，后台自定义点击后续动作

### ISSUE THREAD

**Issue by donald99** [pengyuantao/OnePush#8]
点击通知消息，此方法onNotificationMessageClicked  为什么没有调用？

**Comment by donald99** [comment]
自定义点击后续动作,onNotificationMessageClicked 为什么没有调用？

**Comment by pengyuantao** [comment]
不会呀，你检查下，小米的自定义权限有没有添加。
 
    <permission
        android:name="com.peng.one.push.permission.MIPUSH_RECEIVE"
        android:protectionLevel="signature" />
    
    <uses-permission android:name="com.peng.one.push.permission.MIPUSH_RECEIVE" />
   

我试了，我这是可以的。
![screenshot_2017-09-21-21-12-08-446_com peng one push](https://user-images.githubusercontent.com/10327185/30697554-02806d52-9f12-11e7-90cc-923181895e26.png)

**Comment by donald99** [comment]
服务端给小米推送发消息中的extras字段里面，存在notify_effect=1或2或3，客户端接收到通知消息，点击后确实没有点击事件触发onNotificationMessageClicked 。

**Comment by pengyuantao** [comment]
请参照小米服务端，下面的写法：
https://github.com/pengyuantao/OnePush/blob/master/OnePushService/src/com/peng/one/push/service/xiaomi/XiaomiService.java

**Comment by smoothdvd** [comment]
@donald99 不设置notify_effect才会触发onNotificationMessageClicked
